# Usa uma imagem base do Nginx
FROM nginx:alpine

# Copia o arquivo de configuração customizado
COPY default.conf /etc/nginx/conf.d/default.conf

# Copia todos os arquivos do site para o diretório padrão do Nginx
COPY . /usr/share/nginx/html

# Expõe a porta padrão do Nginx
EXPOSE 80